### ISSUE TITLE
Github deprecated ::set-env

### ISSUE THREAD

**Issue by ericdallo** [jcs090218/setup-emacs-windows#37]
Github deprecated and now is failing runs which use add-path or set-env. More info [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

Run failing example: https://github.com/emacs-lsp/lsp-mode/runs/1415891285

Related: https://github.com/conao3/setup-cask/issues/6

**Comment by jcs090218** [comment]
I think the master branch works? Can you try `jcs090218/setup-emacs-windows@master`? Thanks!

**Comment by ericdallo** [comment]
It's working now, thank you!
